accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'

urlpatterns = [
    path('search/', user_search, name='search'),
    path('invite/', user_invite, name='invite'),
    path('accept/<int:inviteStatus_id>/', user_accept, name='accept'),
    path('signup/', user_signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

board/urls.py
from django.urls import path
from .views import *

app_name = 'board'

urlpatterns = [
    path('create/', board_create, name='board_create'),
    path('delete/<int:board_id>/', board_delete, name='board_delete'),
    path('update/<int:board_id>/', board_update, name='board_update'),
    path('list/', board_list, name='board_list'),
    path('detail/<int:board_id>/', board_detail, name='board_detail'),
    path('comments/<int:board_id>/', comment_create, name='comment_create'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('board/', include('board.urls')),
    path('post/', include('post.urls')),
    path('schedule/', include('schedule.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('extore.urls')),
    path('admin/', admin.site.urls),
    # 라이브 상태일 때 S3 연동 없이, serve 뷰 사용하여 media 연결
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('debug/', include(debug_toolbar.urls)),
    ]

# from django.conf.urls.static import static
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extore/urls.py
from django.urls import path
from .views import *

app_name='extore'

urlpatterns=[
    path('', group_list, name='extore_list'),
    path('extore/detail/<int:group_id>/',group_detail, name='extore_detail'),
    path('extore/create/', group_create, name='extore_create'),
    path('extore/delete/<int:group_id>/', group_delete, name='extore_delete'),
    path('extore/overlap/', group_overlap, name='extore_overlap'),
]

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('list/', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('detail/<int:post_id>/', post_detail, name='detail'),
    path('update/<int:post_id>/', post_update, name='update'),
    path('delete/<int:post_id>/', post_delete, name='delete'),
    path('tags/<tag>/', PostTaggedObjectList.as_view(), name='post_taggedlist'),
    path('comments/<int:post_id>/', comment_create, name='comment_create'),
    path('like/<int:post_id>/', post_like, name='post_like'),
    path('saved/<int:post_id>/', post_saved, name='post_saved'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('last_memory/', last_memory, name='last_memory'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

schedule/urls.py
from django.urls import path
from .views import *

app_name = 'schedule'

urlpatterns = [
    path('', index, name='index'),
    path('create/', schedule_create, name='create'),
    path('list/<int:group_id>/', schedule_list, name='list'),
    path('update/<int:calendarevent_id>/', schedule_update, name='update'),
    path('delete/<int:calendarevent_id>/', schedule_delete, name='delete'),
    path('all_events/<int:group_id>/', all_events, name='all_events'),
]

extore/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone

from accounts.models import User


class Group(models.Model):
    title = models.CharField(max_length=10)
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True, db_index=True, default="")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_groups')
    member = models.ManyToManyField(User, related_name='members_groups', blank=True)
    image = models.ImageField(upload_to='group_images/%Y/%m/%d', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Group, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class InviteStatus(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='invites')
    invited = models.ManyToManyField(User, related_name='invited', blank=True)
    accepted = models.ManyToManyField(User, related_name='accepted', blank=True)
    rejected = models.ManyToManyField(User, related_name='rejected', blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.group.title


class InviteDate(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='invitedDate')
    invited = models.ForeignKey(User, on_delete=models.CASCADE, related_name='invitedDate')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.invited.last_name}{self.invited.first_name} invited from {self.group.title} in {self.created}'

extore/forms.py
from django import forms
from .models import *

# class BoardForm(forms.ModelForm):
#     class Meta:
#         model = Board
#         fields = ['title']


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['title', 'image']

extore/views.py
import math
import random

from django.http import JsonResponse, Http404
from django.utils.text import slugify
from django.shortcuts import render
from .models import Group
from .forms import GroupForm
from post.models import Post
from accounts.models import User

# 익스토어 목록
def group_list(request):
    # group_list = extore 리스트
    if request.user.is_authenticated:
        group_list = request.user.members_groups.all()
        invited_groups = request.user.invited.all()
        invited_dates = request.user.invitedDate.all()
    else:
        group_list = None
        invited_groups = None
        invited_dates = None
    form = GroupForm()

    return render(request, 'extore/extore_index.html', {'group_list': group_list, 'invited_groups':invited_groups, 'invited_dates':invited_dates, 'form':form})


# 익스토어 상세
def group_detail(request, group_id):
    if request.method == 'GET':
        # group = the extore to see detail
        group = Group.objects.get(id=group_id)
        if not request.user in group.member.all():
            raise Http404
        # group_list = extore list
        group_list = request.user.members_groups.all()
        posts = Post.objects.filter(extore_id=group_id)

        page = int(request.GET.get('page', 1))
        paginated_by = 3
        total_count = len(posts)
        total_page = math.ceil(total_count / paginated_by)
        page_range = range(1, total_page + 1)
        start_index = paginated_by * (page - 1)
        end_index = paginated_by * page
        posts = posts[start_index:end_index]

        users = User.objects.all()

        return render(request, 'post/post_list.html', {'object_list': posts, 'group':group, \
                                                       'group_list':group_list, 'users':users, 'total_page':total_page, 'page_range':page_range})


# 익스토어 탈퇴
def group_delete(request, group_id):
    is_ajax = request.POST.get('is_ajax', None)
    if is_ajax:
        group = Group.objects.get(id=group_id)
        if not request.user.is_authenticated:
            return JsonResponse({'notLogin':True})
        if not request.user in group.member.all():
            return JsonResponse({'notMember':True})

        # 탈퇴하려는 그룹에 유저가 한명일 경우, 그룹 전체 삭제
        if group.member.all().count() == 1:
            group.delete()
            return JsonResponse({'leaved': True})

        # 탈퇴하려는 유저가 그룹 방장일 경우, 그 다음 순서에 있는 유저를 방장으로 위임
        if request.user == group.author:
            members = group.member.all()
            count = -1
            for member in members:
                count += 1
                if member == request.user:
                    # count(index)가 맨 마지막 index일 경우 맨 앞에 있는 사람을 방장으로 선정
                    if count == len(members)-1:
                        new_index = 0
                    else:
                        new_index = count+1
                    break

            new_author = members[new_index]
            group.author_id = new_author.id


        group.member.remove(request.user)
        group.save()

        return JsonResponse({'leaved':True})


# 익스토어 생성
def group_create(request):
    if not request.user.is_authenticated:
        raise Http404
    if request.is_ajax():
        # extoreTitle, extoreImage 데이터 모두 전달받지 못한 경우
        if request.POST.get('extoreTitle') == "" and request.FILES.get('extoreImage', None) is None:
            return JsonResponse({'neither_data':True})
        # extoreTitle 길이가 10자리 초과한 경우
        elif len(request.POST.get('extoreTitle')) > 10:
            return JsonResponse({'tooLongTitle':True})
        # extoreTitle 데이터만 전달받지 못한 경우
        elif request.POST.get('extoreTitle') == "":
            return JsonResponse({'no_extoreTitle':True})
        # extoreImage 데이터만 전달받지 못한 경우
        elif request.FILES.get('extoreImage', None) is None:
            return JsonResponse({'no_extoreImage':True})
        # extoreTitle, extoreImage 데이터 모두 전달받은 경우
        else:
            extore_title = request.POST.get('extoreTitle')

            # request에서 전달받은 title이 기존 익스토어 이름과 중복되는지 확인
            if Group.objects.filter(title=extore_title).exists():
                return JsonResponse({'overlap':True})

            # request에서 전달받은 title이 기존 익스토어 이름과 중복안되는 경우
            group = Group.objects.create(title=request.POST.get('extoreTitle'), image=request.FILES.get('extoreImage'), author_id=request.user.id)
            group.member.add(request.user)

            return JsonResponse({'works':True})

    # ajax 요청이 아닌 경우
    return JsonResponse({'not_ajax':True})


# 익스토어 이름 중복 체크
def group_overlap(request):
    if request.is_ajax():
        extore_title = request.POST.get('extoreTitle', None)
        extore_slug = slugify(extore_title, allow_unicode=True)

        if extore_title == "":
            return JsonResponse({'no_data':True})
        # request에서 전달받은 title이 기존 익스토어 이름과 중복되는 경우
        elif Group.objects.filter(slug=extore_slug).exists():
            return JsonResponse({'overlap':True})
        # request에서 전달받은 title이 기존 익스토어 이름과 중복되지 않는 경우
        return JsonResponse({'works':True})
    # ajax 요청이 아닌 경우
    return JsonResponse({'not_ajax':True})

extore/templates/extore/extore_create.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
<div class="row mt-3">
    <div class="col-8">
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table table-striped">
            {{form.as_table}}
            </table>
            <input type="submit" class="btn btn-primary" value="Write">
        </form>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

extore/templates/extore/extore_detail.html
{% extends 'post-base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<hr>
<nav class="navbar navbar-expand-lg navbar-light bg-white text-center">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav extore mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'board:board_list' %}?extore={{group.id}}">Free Talk <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:list' %}?extore={{group.id}}">Post <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:last_memory' %}?extore={{group.id}}">Last Memory <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'schedule:index' %}?extore={{group.id}}">Schedule <span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>
{% load static %}
<div class="row mx-auto">
    <div class="col">
        <div class="container">
            <div class="card" style="width: 12rem; height: 35rem;">
                <div class="card-body">
                    <h6 class="text-center">{{group.title}}</h6>
                    <hr>
                    {% for member in group.member.all %}
                        <div class="profile_img text-center" >
                            <img src="{{member.profile.url}}" >
                            <div class="member_text text-center" style="font-size:15px;">{{member.last_name}}{{member.first_name}}</div>
                            <br>
                            </div>
                    {% endfor %}
                        <div class="profile_img text-center" >
                        <img src="{% static 'images/plus_icon.png' %}" >
                            <div class="member_text text-center" style="font-size:15px;">Add</div>
                            <br>
                        </div>

                    <div class="card-footer text-center text-muted">
                            <h5>Extore List</h5><hr>
                            {% for group in group_list %}
                                <div class="extore_list text-center">
                                    {{group.title}}
                                </div>
                            {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

extore/templates/extore/extore_index.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}
{% load static %}
<style>
    div#navbarSupportedContent{z-index:100;}

    .navbar.navbar-expand-lg{
        height: 40px;
    }
    .group_bar{

    }


    .menu a{
        color: red;
        font-size: 30px;
        font-style: italic;
    }

    .navbar-nav.extore {
        margin-top: -10px;
        position: absolute;
        left: 50%;
        transform: translatex(-50%);
    }

    .extore-img {
        float:left;
        display:inline-block;
        width:70px;
        height:70px;
        border-radius:35px;
        background-size:cover;
        background-repeat:no-repeat;
        background-position:center center;
    }
    .carousel-item {
        z-index: -99px;
    }



</style>
{% endblock %}

{% block content %}
<hr>
<nav class="navbar navbar-expand-sm navbar-light bg-white text-center">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav extore mr-auto">
      <li class="nav-item dropdown">
        <a style="color:black;" class="nav-link dropdown-toggle" href="#" id="dropdownMenuOffset" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,50">
          Extore
        </a>
        {% if user.is_authenticated %}
        <div style="width:250px;" class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
            <div class="dropdown-header text-center"><b>소속 익스토어</b></div>
            <div class="dropdown-divider"></div>
            {% if group_list %}
                <div style="margin: 20px 0 20px 0">
                    {% for group in group_list %}
                    <a class="dropdown-item text-center" href="{% url 'extore:extore_detail' group.id %}">
                        {{group.title}}
                    </a>
                    {% endfor %}
                </div>
            {% else %}
                <p style="margin-top:20px; margin-bottom:20px;" class="text-center">활성화된 익스토어가 없습니다.</p>
            {% endif %}
                <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center"  href="#" data-toggle="modal" data-target="#extoreInvited">초대 알림</a>
                <div class="dropdown-divider"></div>
            <a class="dropdown-item text-center"  href="#" data-toggle="modal" data-target="#extoreCreate">익스토어 생성</a>
        </div>
        {% else %}
        <div style="width:250px;" class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
            <div class="dropdown-header text-center"><b>로그인이 필요합니다.</b></div>
        </div>
        {% endif %}

      </li>
    </ul>
  </div>
</nav>

<div class="main_content">
    {% load static %}

    <!-- exoterInvited Modal -->
    <div class="modal fade" id="extoreInvited" tabindex="-1" role="dialog" aria-labelledby="extoreInvitedLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content" style="z-index:1000;">
          <div class="modal-header">
            <h5 class="modal-title" id="extoreInvitedLabel">초대받은 익스토어</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% load calc %}
              {% if invited_groups %}
                  {% for invited_group in invited_groups %}
                    <div class="card invitation">
                      <div class="card-body" style="padding:15px;">
                        <div class="extore-img" style="background-image:url({{invited_group.group.image.url}});"></div>
                        <div style="float:left;">
                          <h5 style="margin-left:20px; margin-bottom:0;">{{invited_group.group.title}}</h5>
                          <p style="display:inline-block; margin:10px 15px 0 20px; color:grey;">방장: {{invited_group.group.author.last_name}}{{invited_group.group.author.first_name}}</p>
                          <p style="display:inline-block; margin:10px 0 0 0; color:grey;">인원: {{invited_group.group.member.count}}</p>
                        </div>
                        <p style="display:inline-block; float:right;">{{invited_group|same_invitation_time_since:invited_dates}}</p>
                        <div style="clear:left;"></div>
                        <div style="float:right;">
                          <a href="{% url 'accounts:accept' invited_group.id %}" class="invite-response btn btn-primary">승락</a>
                          <a href="{% url 'accounts:accept' invited_group.id %}" class="invite-response btn btn-secondary">거부</a>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
              {% else %}
              <p style="text-align:center;">초대받은 익스토어가 없습니다.</p>
              {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- extoreCreate Modal -->
    <div class="modal fade" id="extoreCreate" tabindex="-1" role="dialog" aria-labelledby="extoreCreateLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content" style="z-index:1000;">
          <div class="modal-header">
            <h5 class="modal-title" id="extoreCreateLabel">새로운 익스토어 생성</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form id="extoreCreateModal" action="{% url 'extore:extore_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="extore-title-div input-group mb-3">
                  <input type="text" class="form-control extoreTitle" name="extoreTitle" placeholder="생성할 익스토어 이름을 입력해주세요." aria-label="생성할 익스토어 이름을 입력해주세요." aria-describedby="button-addon2">
                  <div class="input-group-append">
                    <a href="{% url 'extore:extore_overlap' %}" class="overlap-check btn btn-outline-secondary" type="button" id="button-addon2">중복체크</a>
                  </div>
                </div>
                <div class="input-group mb-3">
                    <input type="file" name="extoreImage" class="extoreImage"> <!--multiple 입력하면 다수 이미지 선택 가능-->
                </div>
                <div style="float:right;">
                    <input type="submit" class="btn btn-primary" value="생성하기">
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>


    <!-- Carousel -->
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner" >
        <div class="carousel-item active" data-interval="5000">
          <img src="{% static 'images/memory1.jpg' %}" class=" w-100">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/memory3.jpg' %}" class="d-block w-100">
        </div>
        <div class="carousel-item" >
          <img src="{% static 'images/memory4.jpg' %}" class="d-block w-100">
        </div>
      </div>
      <a href="#carouselExampleFade" data-slide="prev"></a>
      <a href="#carouselExampleFade" data-slide="next"></a>
    </div>


</div>

{% endblock %}

{% block extra_script %}
<script>
$(function(){
    $('.invite-response').click(function(e){
        e.preventDefault();
        url = $(e.currentTarget).attr('href');
        result = $(e.currentTarget).text();
        keepGoing = confirm(result+'하시겠습니까?');

        if(keepGoing == true){
            $.ajax({
                url : url,
                method : "POST",
                data : {
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                    'result' : result,
                    'is_ajax' : true,
                },
            }).done(function(data){
                if(data.accepted){
                    alert('축하합니다!\n'+"'"+data.groupTitle+"'"+'의 회원이 되었습니다.');
                    location.reload();
                }
                if(data.rejected){
                    alert("'"+data.groupTitle+"'"+'의 초대 요청을 거절하였습니다.');
                    location.reload();
                }
            });
        }
    });

    // carousel 이미지 변경되는 시간 간격 설정
    $('.carousel').carousel({
      interval: 3000
    })

    // 익스토어 이름 중복 체크
    $('.overlap-check').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var extoreTitle = $(this).parent().siblings('.extoreTitle').val();
        console.log(url);
        console.log(extoreTitle);
        $.ajax({
            url : url,
            method : "POST",
            data : {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'extoreTitle' : extoreTitle,
                'is_ajax' : true,
            },
        }).done(function(data){
            if(data.overlap){
                alert("이미 사용중인 이름입니다. 다른 이름으로 입력해주세요.");
            } else if(data.works) {
                alert("사용할 수 있는 이름입니다.");
            } else if(data.no_data) {
                alert("익스토어 이름을 입력하시고, 중복 체크를 진행해주세요.");
            } else {
                alert("정상적인 요청이 아닙니다.");
            }
        });
    });

    // 익스토어 생성
    $('#extoreCreateModal').submit(function(e){
        e.preventDefault();
        var url = $(this).attr('action');
        var form = $(this)[0];
        var formData = new FormData(form);

        formData.set("extoreImage", $('.extoreImage')[0].files[0]);

        var extoreTitle = $(this).children('.extore-title-div').children('.extoreTitle').val();

        $.ajax({
            url : url,
            enctype: 'multipart/form-data',
            processData: false,
            contentType: false,
            cache: false,
            type: "POST",
            data : formData,
        }).done(function(data){
            if(data.overlap){
                alert('\n이미 사용중인 이름입니다. 다른 이름으로 입력해주세요.');
            } else if(data.works) {
                alert("\n'"+extoreTitle+"' "+'익스토어를 생성하였습니다.');
                location.reload();
            } else if(data.tooLongTitle) {
                alert('\n익스토어명은 띄어쓰기를 포함해 10자리를 초과할 수 없습니다.');
            } else if(data.neither_data){
                alert('\n생성할 익스토어 이름을 입력해주시고, 배경 이미지 파일을 업로드해주세요.');
            } else if(data.no_extoreTitle){
                alert('\n생성할 익스토어 이름을 입력해주세요.');
            } else if(data.no_extoreImage){
                alert('\n생성할 익스토어 배경 이미지 파일을 업로드해주세요.');
            } else {
                alert('\n정상 요청이 아닙니다.');
            }
        });
    });


});
</script>
{% endblock %}

extore/templates/extore/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>