board/urls.py
from django.urls import path
from .views import *

app_name = 'board'

urlpatterns = [
    path('create/', board_create, name='board_create'),
    path('delete/<int:board_id>/', board_delete, name='board_delete'),
    path('update/<int:board_id>/', board_update, name='board_update'),
    path('list/', board_list, name='board_list'),
    path('detail/<int:board_id>/', board_detail, name='board_detail'),
    path('comments/<int:board_id>/', comment_create, name='comment_create'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('board/', include('board.urls')),
    path('post/', include('post.urls')),
    path('schedule/', include('schedule.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('extore.urls')),
    path('admin/', admin.site.urls),
    # 라이브 상태일 때 S3 연동 없이, serve 뷰 사용하여 media 연결
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('debug/', include(debug_toolbar.urls)),
    ]

# from django.conf.urls.static import static
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('list/', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('detail/<int:post_id>/', post_detail, name='detail'),
    path('update/<int:post_id>/', post_update, name='update'),
    path('delete/<int:post_id>/', post_delete, name='delete'),
    path('tags/<tag>/', PostTaggedObjectList.as_view(), name='post_taggedlist'),
    path('comments/<int:post_id>/', comment_create, name='comment_create'),
    path('like/<int:post_id>/', post_like, name='post_like'),
    path('saved/<int:post_id>/', post_saved, name='post_saved'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('last_memory/', last_memory, name='last_memory'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

board/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.urls import reverse

from extore.models import Group

User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True, allow_unicode=True, db_index=True)

    def __str__(self):
        return self.title


class Board(models.Model):
    extore = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='boards')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='boards')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='boards')
    title = models.CharField(max_length=20, blank=True)
    text = RichTextUploadingField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.author}-{self.category}'

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('board:detail', args=[self.id])


class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    nickname = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='board_comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.nickname.username}님의 댓글'

    class Meta:
        ordering = ['-created']

board/forms.py
from django import forms
from .models import *

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['category', 'title', 'text']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['text'].widget = forms.TextInput()
        self.fields['text'].widget.attrs = {'class':'form-control','placeholder':'댓글을 입력하세요.'}

board/views.py
import math

from django.db.models import Q
from django.http import JsonResponse, Http404
from django.template.loader import render_to_string
from django.utils.text import slugify
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from django.urls import reverse
from django.contrib import messages
from .forms import BoardForm, CommentForm
from .models import *
from accounts.models import User



def board_create(request):
    if request.method == "POST":
        form = BoardForm(request.POST)
        form.instance.author_id = request.user.id
        group_id = request.POST.get('group_id', None)
        form.instance.extore_id = group_id
        group = Group.objects.get(pk=group_id)
        group_list = request.user.members_groups.all()

        if form.is_valid():
            form.save()

            page = int(request.GET.get('page', 1))
            paginated_by = 3
            board_list = Board.objects.filter(extore_id=group_id)
            total_count = len(board_list)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            board_list = board_list[start_index:end_index]

            users = User.objects.all()

            current_top_num = len(Board.objects.filter(extore_id=group_id)) - paginated_by * (page - 1)

            return render(request, 'board/board_list.html', \
                          {'board_list': board_list, 'group': group, 'group_list': group_list, \
                           'users': users, 'total_page': total_page, 'page_range': page_range,
                           'currentTopNum': current_top_num})

        raise Http404
    # 게시물 작성 화면 이동 시,
    else:
        group_id = request.GET.get('extore', None)
        if group_id:
            form = BoardForm()
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()
            users = User.objects.all()
            return render(request, 'board/board_create.html', {'form': form, 'group': group, 'group_list': group_list, 'users': users})
        raise Http404




def board_list(request):
    group_id = request.GET.get('extore', None) if request.method=="GET" else request.POST.get('extore', None)

    if group_id:
        group = Group.objects.get(id=group_id)
        group_list = request.user.members_groups.all()
        board_list = Board.objects.filter(extore_id=group_id)
        users = User.objects.all()

        page = int(request.GET.get('page', 1))
        paginated_by = 3

        search_type = request.POST.getlist('search_type', None) if request.method=="POST" else request.GET.get('searchType', None)

        search_q = None
        search_key = request.POST.get('search_key', None) if request.method=="POST" else request.GET.get('searchKey', None)

        # 검색어 입력한 경우
        if search_key:
            if 'title' in search_type:
                temp_q = Q(title__icontains=search_key)
                search_q = search_q | temp_q if search_q else temp_q
            if 'text' in search_type:
                temp_q = Q(text__icontains=search_key)
                search_q = search_q | temp_q if search_q else temp_q
            if 'realName' in search_type:
                last_name = search_key[0]
                first_name = search_key[1:]
                temp_q = Q(author__last_name=last_name) & Q(author__first_name=first_name)
                search_q = search_q | temp_q if search_q else temp_q
            if len(search_type) == 0:
                total_count = len(board_list)
                total_page = math.ceil(total_count / paginated_by)
                page_range = range(1, total_page + 1)
                start_index = paginated_by * (page - 1)
                end_index = paginated_by * page
                board_list = board_list[start_index:end_index]
                current_top_num = len(Board.objects.filter(extore_id=group_id)) - paginated_by * (page - 1)
                return render(request, 'board/board_list.html', \
                              {'board_list': board_list, 'group': group, 'group_list': group_list, \
                               'users': users, 'total_page': total_page, 'page_range': page_range,
                               'currentTopNum': current_top_num})

            board_list = board_list.filter(search_q)
            total_count = len(board_list)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            board_list = board_list[start_index:end_index]
            return render(request, 'board/board_list.html', \
                      {'board_list': board_list, 'group': group, 'group_list': group_list, \
                       'users': users, 'total_page': total_page, 'page_range': page_range, 'searchKey':search_key, 'searchType':search_type})

        # 검색어 입력하지 않고 목록 조회하는 경우
        total_count = len(board_list)
        total_page = math.ceil(total_count / paginated_by)
        page_range = range(1, total_page + 1)
        start_index = paginated_by * (page - 1)
        end_index = paginated_by * page
        board_list = board_list[start_index:end_index]
        current_top_num = len(Board.objects.filter(extore_id=group_id)) - paginated_by*(page-1)
        return render(request, 'board/board_list.html',\
                      {'board_list':board_list, 'group':group, 'group_list':group_list,\
                       'users':users, 'total_page':total_page, 'page_range':page_range, 'currentTopNum':current_top_num})

    raise Http404


def board_detail(request, board_id):
    if request.method == 'GET':
        board = Board.objects.get(id=board_id)
        group_id = request.GET.get('extore', None)

        if not request.user in Group.objects.get(pk=group_id).member.all():
            raise Http404

        if group_id:
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()

            comment_form = CommentForm()
            comments = board.comments.all()
            users = User.objects.all()
            return render(request, 'board/board_detail.html', {'board':board, 'comments':comments, 'comment_form':comment_form, 'group':group, 'group_list':group_list, 'users':users})

    raise Http404


def board_update(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author and not request.user.is_staff:
        raise Http404

    if request.method == 'POST':
        group_id = request.POST.get('group_id', None)
        form = BoardForm(request.POST, request.FILES, instance=board)
        form.instance.author_id = request.user.id
        form.instance.extore_id = group_id
        if form.is_valid():
            form.save()
            group = Group.objects.get(pk=group_id)
            group_list = request.user.members_groups.all()

            page = int(request.GET.get('page', 1))
            paginated_by = 3
            board_list = Board.objects.filter(extore_id=group_id)
            total_count = len(board_list)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            board_list = board_list[start_index:end_index]

            users = User.objects.all()

            current_top_num = len(Board.objects.filter(extore_id=group_id)) - paginated_by*(page-1)

            return render(request, 'board/board_list.html',\
                          {'board_list':board_list, 'group':group, 'group_list':group_list,\
                           'users':users, 'total_page':total_page, 'page_range':page_range, 'currentTopNum':current_top_num})

    else:
        form = BoardForm(instance=board)
        group_id = request.GET.get('extore', None)
        if group_id:
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()
            users = User.objects.all()
            return render(request, 'board/board_update.html', {'form':form, 'group': group, 'group_list': group_list, 'user': users})
        return Http404


def board_delete(request, board_id):
    if request.is_ajax():
        board = Board.objects.get(id=board_id)
        # 삭제 요청한 유저가 해당 글 작성자가 아니거나, staff가 아닌 경우
        if board.author != request.user and not request.user.is_staff:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return JsonResponse({'noAuthor': True})
        # 삭제 요청한 유저가 해당 글 작성자 혹은 staff 인 경우
        board.delete()
        return JsonResponse({'works':True})
    # ajax 요청이 아닌 경우
    raise Http404


def comment_create(request, board_id):
    is_ajax = request.POST.get('is_ajax')
    board = Board.objects.get(pk=board_id)
    if not request.user in board.extore.member.all():
        raise Http404
    comment_form = CommentForm(request.POST)
    comment_form.instance.nickname_id = request.user.id
    comment_form.instance.board_id = board_id
    if comment_form.is_valid():
        comment = comment_form.save()

    if is_ajax:
        html = render_to_string('board/comment_single.html', {'comment':comment, 'user':request.user})
        return JsonResponse({'html':html})

    return redirect(board)


def comment_list(request, board_id):
    board = Board.objects.get(id=board_id)
    if not request.user in board.extore.member.all():
        raise Http404
    comments = board.comments.all()

    return render(request, 'board/comment_list', {'comments':comments})


def comment_like(request, comment_id):
    is_ajax = request.GET.get('is_ajax') if 'is_ajax' in request.GET else request.POST.get('is_ajax',False)
    comment = Comment.objects.get(id=comment_id)

board/templates/board/board_create.html
{% extends 'post-base.html' %}

{% block title %}

{% endblock %}

{% block content %}
<div class="row mt-3">
    <div class="col-8">
        <form action="" method="post"  enctype="multipart/form-data">
            <input type="hidden" name="group_id" value="{{group.id}}">
            {% csrf_token %}
            {{form.media}}
            <table class="table table-striped">
            {{form.as_table}}
            </table>
            <input type="submit" class="btn btn-primary" value="Write">
        </form>
    </div>
    <div class="col"></div>
</div>

<style>
    div#navbarSupportedContent{z-index:9999;}

    .navbar-nav.extore {
        margin-top: -10px;
        position: absolute;
        left: 50%;
        transform: translatex(-50%);
    }
    .navbar.navbar-expand-lg{
        height: 40px;
    }
</style>

{% endblock %}

board/templates/board/board_detail.html
{% extends 'post-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}
<style>
    #board-list {
        display: inline-block;
        text-align:left;
    }
    .back-to-page {
        width:100px;
        float:right;
        margin-bottom:20px;
    }
    .board-update:hover {
        text-decoration: none;
    }
    .board-delete:hover {
        text-decoration: none;
    }
</style>
{% endblock %}

{% block content %}
<div id="board-list">
    <div>
        <a href="{% url 'board:board_list' %}?extore={{group.id}}" class="btn btn-primary back-to-page">돌아가기</a>
    </div>
   <div class="card" style="width: 40rem;">
       <div id="profiles">
           <div class="img-profile" style="background-image:url({{board.author.profile.url}})"></div>
           <a class="a-tag name-profile" href="#">{{board.author.last_name}}{{board.author.first_name}}</a>
           <p style="float:right; margin-right:10px; color:rgb(185,185,185);">
               {% load calc %}
               {{board.created|time_since}}
           </p>
       </div>
       <hr style="margin:0;">
       <div class="btn btn-light">
           <h6 style="display:inline-block; float:left; color:grey;">{{board.category}}</h6>
           <h7 style="display:inline-block;">{{board.title}}</h7>
       </div>
       <div class="card-body" style="padding:1.25rem 1.25rem 0.5rem 1.25rem;">
           <ul style="list-style-type:none; padding:0px;">
               <li>
                   <div style="padding:5px;">{{board.text|safe}}</div>
               </li>
               <li>
                   {% if user|author_or_staff:object.author %}
                   <a class="board-delete" href="{% url 'board:board_delete' board.id %}" style="float:right;">삭제</a>
                   <a class="board-update" href="{% url 'board:board_update' board.id %}?extore={{group.id}}" style="float:right;margin-right:10px;">수정</a>
                   <div class="after-click-update"></div>
                   {% endif %}
               </li>
           </ul>
           <div style="height:10px; clear:both;"></div>
       </div>
   </div>
   <div class="card" style="width: 40rem; margin-top:-10px;">
      <div>
          <div class="img-profile" style="background-image:url({{user.profile.url}})"></div>
          <div style="float:right; height:70px; line-height:70px;">
              <div style="display:inline-block; vertical-align:middle; line-height:normal;">
                  <form action="{% url 'board:comment_create' board.id %}" method="post" id="comment_form">
                      {% csrf_token %}
                      <input type="hidden" name="is_ajax" value="">
                      <div class="row" style="width:590px; padding-right:10px;">
                          <div id="comment_write" class="col-8" style="padding:0 0 0 5px;">{{comment_form.text}}</div>
                          <div class="col">
                              <input type="submit" value="댓글 입력" class="btn btn-outline-primary form-control">
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
      <div id="comment_list">
        {% include 'board/comment_list.html' %}
      </div>
   </div>

</div>


<style>
    div#navbarSupportedContent{z-index:9999;}

    .navbar-nav.extore {
        margin-top: -10px;
        position: absolute;
        left: 50%;
        transform: translatex(-50%);
    }
    .navbar.navbar-expand-lg{
        height: 40px;
    }
</style>

{% endblock %}

{% block extra_script %}
<script type="text/javascript">
$(function () {
    $("#comment_form").submit(function(e){
        e.preventDefault();
        $('input[name="is_ajax"]').val("1");
        url = $(this).attr('action');
        params = $(this).serialize(); // 현재 값들을 하나로 모은다.
        $.ajax({
            url: url,
            method: "POST",
            data: params,
        }).done(function(data){
            location.reload();
        });
    });

    $(".btn-comment-like").click(function(e){
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href')
        console.log(url);
        $.ajax({
            url:url,
            method:"POST",
            data:{
                'csrfmiddlewaretoken':'{{csrf_token}}',
                'is_ajax':true,
            },
        }).done(function(data){
            if(data.works){
                str_comment_like = selected_object.html().trim();
                if(str_comment_like.match(/[0-9]+/g)==null){
                    selected_object.html("&emsp;좋아요 1개")
                }
                else{
                    int_comment_like = str_comment_like.match(/[0-9]+/g);
                    comment_like = parseInt(int_comment_like[0]) + 1;
                    selected_object.html("&emsp;좋아요 "+comment_like+"개")
                }
            }
        });
    });

    $(".btn-comment-delete").click(function(e){
        e.preventDefault();
        var input = confirm('댓글을 삭제하시겠습니까?');
        if (input==true){
            selected_object = $(e.currentTarget);
            url = selected_object.attr('href')+"?is_ajax=1";
            console.log(url);
            $.ajax({
                url: url,

            }).done(function(data){
                if (data.works){
                    selected_object.parents('.comment-single').remove();
                }
            });
        }
    });

    $('.btn-comment-update').click(function(e) {
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href')+'?is_ajax=1';
        comment = selected_object.siblings('p').children('.comment-text');
        input = "<input type='text' class='update-text' value='"+comment.text()+"'>";
        comment.html(input);
        $('.update-text').keypress(function(e){
            if (e.keyCode==13) {
                text = $(this).val();
                $.ajax({
                    url:url,
                    data:{
                        text:text
                    }
                }).done(function(data) {
                    if(data.works) {
                        comment.text(text);
                    }
                });
            }
        });
    });
    $('.board-delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var check = confirm('해당 게시물을 삭제하시겠습니까?');
        if(check==true) {
            $.ajax({
                url : url,
            }).done(function(data){
                if(data.works){
                    alert('해당 게시물이 삭제되었습니다.');
                    window.location.href = "{% url 'board:board_list' %}?extore={{group.id}}"
                } else if(data.noAuthor){
                    alert('삭제할 권한이 없습니다.');
                } else {
                    alert('정상 요청이 아닙니다.');
                }
            });
        }
    });

});

</script>
{% endblock %}

board/templates/board/board_list.html
{% extends 'post-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}
<style>
#board-list {
    width:800px;
    display: inline-block;
}

.board-write {
    width:100px;
    float:right;
    margin-bottom:20px;
}
</style>
{% endblock %}

{% block content %}
{% load static %}

<div id="board-list">
    <div>
        <a href="{% url 'board:board_create'%}?extore={{group.id}}" class="btn btn-primary board-write" >글 작성</a>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          {% if currentTopNum %}
              <th scope="col">Number</th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Date</th>
          {% else %}
              <th>Title</th>
              <th>Author</th>
              <th>Date</th>
          {% endif %}

        </tr>
      </thead>
      <tbody>
            {% load calc %}
            {% for board in board_list %}
            <tr>
                {% if currentTopNum %}
                    <th scope="row"><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{currentTopNum|list_index:forloop.counter0}}</a></th>
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.title}}</a></td>
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.author.last_name}}{{board.author.first_name}}</a></td>
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.created|date:"Y-m-d D"}}</a></td>
                {% else %}
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.title}}</a></td>
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.author.last_name}}{{board.author.first_name}}</a></td>
                    <td><a class="nav-link " style="color:black;" href="{% url 'board:board_detail' board.id %}?extore={{group.id}}">{{board.created|date:"Y-m-d D"}}</a></td>
                {% endif %}
            </tr>
            {% endfor %}
      </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for page in page_range %}
            {% if searchKey %}
            <li class="page-item">
                <a class="page-link" href="{% url 'board:board_list' %}?extore={{group.id}}&searchKey={{searchKey}}&searchType={{searchType}}&page={{page}}">{{page}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{% url 'board:board_list' %}?extore={{group.id}}&page={{page}}">{{page}}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>

    <form action="{% url 'board:board_list' %}" method="post" id="search_form">
        {% csrf_token %}
        <input type="hidden" name="extore" value="{{group.id}}">
        <div class="form-row align-items-center justify-content-center">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="title" name="search_type" checked>
                <label class="form-check-label" for="inlineCheckbox2">제목</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="realName" name="search_type">
                <label class="form-check-label" for="inlineCheckbox1">작성자</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="text" name="search_type">
                <label class="form-check-label" for="inlineCheckbox3">본문</label>
            </div>
        </div>
        <div class="form-row align-items-center justify-content-center">
            <div class="col-sm-3 my-1">
                <input type="text" class="form-control" placeholder="검색어" name="search_key">
            </div>

            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">검색하기</button>
            </div>
        </div>
    </form>


</div>


{% endblock %}

board/templates/board/board_update.html
{% extends 'post-base.html' %}
{% block title %}{% endblock %}

{% block extra_style %}
<style>
#board-list {
    display: inline-block;
    text-align:left;
}
</style>
{% endblock %}

{% block content %}
<div id="board-list">
    <form action="" method="post"  enctype="multipart/form-data">
        <input type="hidden" name="group_id" value="{{group.id}}">
        {% csrf_token %}
        {{form.media}}
        <table class="table table-striped">
        {{form.as_table}}
        </table>
        <div style="float:left;">
            <a href="{% url 'board:board_list' %}?extore={{group.id}}" class="btn btn-outline-primary" style="margin-right:10px;">목록</a>
            <input type="submit" class="btn btn-primary" value="수정하기">
        </div>
    </form>
</div>
{% endblock %}

board/templates/board/comment_delete.html
{% extends 'post-base.html' %}
{% block content %}
<form action="" method="post">
    <div class="alert alert-danger">해당 댓글을 삭제하실건가요?</div>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="댓글 삭제" class="btn btn-outline-danger">
</form>
{% endblock %}

board/templates/board/comment_list.html
{% if comments %}
    {% for comment in comments %}
        {% include 'board/comment_single.html' %}
    {% endfor %}
{% endif %}

board/templates/board/comment_single.html
<div class="comment-single" style="margin-bottom: 20px;">
    <div class="img-profile" style="background-image:url({{comment.nickname.profile.url}})"></div>
    <div style="float:left; height:100%; width:550px; line-height:100%;">
        <div style="display:inline-block; vertical-align:middle; line-height:normal;">
            <p style="padding:10px; border-radius:25px; background-color:rgb(237,237,237); display:inline-block; margin:0">
                <a style="color:rgb(37,71,194); font-weight:bold;" href="#">{{comment.nickname.last_name}}{{comment.nickname.first_name}}</a>&emsp;
                <a class="comment-text">{{comment.text}}</a>
            </p>
            <a class="btn-comment-like" href="{% url 'board:comment_like' comment.id %}">&emsp;좋아요 {% if comment.like %}{{comment.like}}개{% endif %}</a>

            {% if user.is_superuser or comment.nickname == user %}
            <a class="btn-comment-update" href="{% url 'board:comment_update' comment.id %}">&emsp;수정</a>
            <a class="btn-comment-delete" href="{% url 'board:comment_delete' comment.id %}">삭제</a>
            {% endif %}
        </div>
    </div>
    <div style="clear:both;"></div>
</div>

board/templates/board/comment_update.html
{% extends 'post-base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-outline-warning">
</form>
{% endblock %}