config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('board/', include('board.urls')),
    path('post/', include('post.urls')),
    path('schedule/', include('schedule.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('extore.urls')),
    path('admin/', admin.site.urls),
    # 라이브 상태일 때 S3 연동 없이, serve 뷰 사용하여 media 연결
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('debug/', include(debug_toolbar.urls)),
    ]

# from django.conf.urls.static import static
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('list/', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('detail/<int:post_id>/', post_detail, name='detail'),
    path('update/<int:post_id>/', post_update, name='update'),
    path('delete/<int:post_id>/', post_delete, name='delete'),
    path('tags/<tag>/', PostTaggedObjectList.as_view(), name='post_taggedlist'),
    path('comments/<int:post_id>/', comment_create, name='comment_create'),
    path('like/<int:post_id>/', post_like, name='post_like'),
    path('saved/<int:post_id>/', post_saved, name='post_saved'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('last_memory/', last_memory, name='last_memory'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

post/models.py
from django.db import models
from tagging.fields import TagField
from location_field.models.plain import PlainLocationField
from django.contrib.auth import get_user_model
from django.urls import reverse
from extore.models import Group


User = get_user_model()
class Post(models.Model):
    extore = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="posts")
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    text = models.TextField()
    tags = TagField(blank=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    location = PlainLocationField(based_fields=['city'], zoom=7, blank=True, null=True) # default="37.54965563216749,127.0469284057617"
    created = models.DateTimeField(auto_now_add=False)
    updated = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, related_name="like_post", blank=True)
    saved = models.ManyToManyField(User, related_name="saved_post", blank=True)

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('post:detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0)

    def __str__(self):
        try:
            return self.author.username + "의 댓글"
        except AttributeError:
            return '비회원의 댓글'


    class Meta:
        ordering = ['-id']

post/forms.py
from django import forms
from .models import *
# from django.forms.widgets import ClearableFileInput
#
#
# class CustomImageFieldWidget(ClearableFileInput):
#     template_with_clear = '<label for="%(clear_checkbox_id)s">%(clear)s %(clear_checkbox_label)s</label>'


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'text', 'tags', 'created'] # city, location

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].label = ''
        self.fields['text'].label = ''
        self.fields['text'].widget.attrs = {'class':'form-control','placeholder':'내용을 입력하세요.'}
        self.fields['tags'].label = ''
        self.fields['tags'].widget.attrs = {'class':'form-control','placeholder': '태그를 입력하세요.'}
        # self.fields['city'].label = ''
        # self.fields['city'].widget.attrs = {'class':'form-control','placeholder': '위치를 추가하세요.(ex. Seoul)'}
        # self.fields['location'].label = ''
        # self.fields['location'].widget.attrs = {'class':'form-control','placeholder':'위도,경도'}
        self.fields['created'].widget.attrs = {'class':'form-control','placeholder':'ex) 2019-06-26'}
        


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].label = ''
        self.fields['text'].widget = forms.TextInput()
        self.fields['text'].widget.attrs = {'class':'form-control','placeholder':'댓글을 입력하세요.'}

post/views.py
import math

from django.db.models import Q
from django.shortcuts import redirect, render, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.contrib import messages
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from .models import *
from .forms import *
from accounts.models import User


def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        group_id = request.POST.get('group_id', None)
        form.instance.author_id = request.user.id
        form.instance.extore_id = group_id
        if form.is_valid():
            form.save()

            posts = Post.objects.filter(extore_id=group_id)
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()

            page = int(request.GET.get('page', 1))
            paginated_by = 3

            search_type = request.POST.getlist('search_type', None) if request.method == "POST" else request.GET.get('searchType', None)

            search_q = None
            search_key = request.POST.get('search_key', None) if request.method == "POST" else request.GET.get('searchKey', None)

            total_count = len(posts)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            posts = posts[start_index:end_index]

            users = User.objects.all()
            return render(request, 'post/post_list.html', {'object_list': posts, 'group': group, \
                                                           'group_list': group_list, 'users': users,
                                                           'total_page': total_page, 'page_range': page_range})
    else:
        group_id = request.GET.get('extore', None)
        if group_id:
            form = PostForm()
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()
            users = User.objects.all()
            return render(request, 'post/post_create.html', {'form':form, 'group':group, 'group_list':group_list, 'users':users})
        raise Http404



def post_list(request):
    group_id = request.GET.get('extore', None) if request.method == "GET" else request.POST.get('extore', None)
    if group_id:
        posts = Post.objects.filter(extore_id=group_id)
        group = Group.objects.get(id=group_id)
        group_list = request.user.members_groups.all()
        users = User.objects.all()

        page = int(request.GET.get('page', 1))
        paginated_by = 3

        search_type = request.POST.getlist('search_type', None) if request.method == "POST" else request.GET.get('searchType', None)

        search_q = None
        search_key = request.POST.get('search_key', None) if request.method == "POST" else request.GET.get('searchKey', None)

        # 검색어 입력한 경우
        if search_key:
            if 'text' in search_type:
                temp_q = Q(text__icontains=search_key)
                search_q = search_q | temp_q if search_q else temp_q
            if 'realName' in search_type:
                last_name = search_key[0]
                first_name = search_key[1:]
                temp_q = Q(author__last_name=last_name) & Q(author__first_name=first_name)
                search_q = search_q | temp_q if search_q else temp_q
            if len(search_type) == 0:
                total_count = len(posts)
                total_page = math.ceil(total_count / paginated_by)
                page_range = range(1, total_page + 1)
                start_index = paginated_by * (page - 1)
                end_index = paginated_by * page
                posts = posts[start_index:end_index]
                return render(request, 'post/post_list.html', {'object_list': posts, 'group': group, \
                                                               'group_list': group_list, 'users': users,
                                                               'total_page': total_page, 'page_range': page_range})

            posts = posts.filter(search_q)
            total_count = len(posts)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            posts = posts[start_index:end_index]
            return render(request, 'post/post_list.html', \
                          {'object_list': posts, 'group': group, 'group_list': group_list, \
                           'users': users, 'total_page': total_page, 'page_range': page_range, 'searchKey': search_key,
                           'searchType': search_type})

        # 검색어 입력하지 않고 목록 조회하는 경우
        total_count = len(posts)
        total_page = math.ceil(total_count / paginated_by)
        page_range = range(1, total_page + 1)
        start_index = paginated_by * (page - 1)
        end_index = paginated_by * page
        posts = posts[start_index:end_index]
        return render(request, 'post/post_list.html', {'object_list': posts, 'group':group, \
                                                       'group_list':group_list, 'users':users, 'total_page':total_page, 'page_range':page_range})

    raise Http404


def post_detail(request, post_id):
    if request.method == 'GET':
        group_id = request.GET.get('extore', None)
        if group_id:
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()
            post = Post.objects.get(pk=post_id)

            comment_form = CommentForm()
            comments = post.comments.all()
            users = User.objects.all()

            return render(request, 'post/post_detail.html', {'object':post, 'comments':comments, 'comment_form':comment_form, 'group':group, 'group_list':group_list, 'users':users})
    raise Http404


def post_delete(request, post_id):
    post = Post.objects.get(pk=post_id)
    # 로그인한 유저가 작성자일 경우, 해당 포스트 삭제 버튼 보이도록
    # ajax post요청일 경우, detail 페이지로 이동
    if request.is_ajax():
        if post.author != request.user and not request.user.is_staff:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return JsonResponse({'noAuthor':True})
        post.delete()
        return JsonResponse({'works':True})

    # ajax 요청이 아닌경우, Http404 에러 발생
    raise Http404


def post_update(request, post_id):
    if request.is_ajax():
        post = Post.objects.get(pk=post_id)
        text = request.POST.get('text')

        # 수정 요청한 유저가 글 작성자 혹은 staff 가 아닌 경우
        if request.user != post.author and not request.user.is_staff:
            return JsonResponse({'noAuthor':True})

        # 수정 요청한 유저가 글 작성자 혹우은 staff인 경우
        post.text = text
        post.save()
        return JsonResponse({'works': True})

    # ajax 요청이 아닌 경우
    raise Http404


# 태그 기능 관련
from tagging.views import TaggedObjectList
from tagging.models import TaggedItem
from django.core.exceptions import ImproperlyConfigured

class PostTaggedObjectList(TaggedObjectList):
    model = Post
    allow_empty = True
    template_name = 'post/post_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        group_id = self.request.GET.get('extore', None)
        group = Group.objects.get(id=group_id)
        group_list = self.request.user.members_groups.all()
        users = User.objects.all()

        context_data['group'] =  group
        context_data['group_list'] = group_list
        context_data['users'] = users

        return context_data

    def get_queryset(self):
        super().get_queryset()
        group_id = self.request.GET.get('extore', None)
        posts = Post.objects.filter(extore_id=group_id)

        self.queryset_or_model = posts
        self.tag_instance = self.get_tag()
        return TaggedItem.objects.get_by_model(
            self.queryset_or_model, self.tag_instance)


# from django.views.generic import TemplateView
# class TagList(TemplateView):
#     template_name = 'post/tag_list.html'


def comment_create(request, post_id):
    is_ajax = request.POST.get('is_ajax')
    post = Post.objects.get(pk=post_id)
    comment_form = CommentForm(request.POST)
    comment_form.instance.author_id = request.user.id
    comment_form.instance.post_id = post_id
    if comment_form.is_valid():
        comment = comment_form.save()
    if is_ajax:
        html = render_to_string('post/comment_single.html',{'comment':comment, 'user':request.user})
        return JsonResponse({'html':html})

    return redirect(post)



from urllib.parse import urlparse
def post_like(request, post_id):
    post = Post.objects.get(pk=post_id)
    is_ajax, data = (request.GET.get('is_ajax'), request.GET) if 'is_ajax' in request.GET else (
    request.POST.get('is_ajax', False), request.POST)

    if is_ajax:
        if request.user in post.like.all():
            post.like.remove(request.user)
            print("좋아요 해제")
            return JsonResponse({'liked':False})
        else:
            post.like.add(request.user)
            print("좋아요 클릭")
            return JsonResponse({'liked': True})

    if request.method == "GET":
        # if not request.user.is_authenticated:
        #     return HttpResponseRedirect('/accounts/signin')
        if request.user in post.like.all():
            post.like.remove(request.user)
        else:
            post.like.add(request.user)
        referer_url = request.META.get('HTTP_REFERER')
        path = urlparse(referer_url).path
        return HttpResponseRedirect(path)

def post_saved(request, post_id):
    post = Post.objects.get(pk=post_id)
    is_ajax, data = (request.GET.get('is_ajax'), request.GET) if 'is_ajax' in request.GET else (request.POST.get('is_ajax', False), request.POST)

post/templates/post/comment_delete.html
{% extends 'post-base.html' %}
{% block content %}
<form action="" method="post">
    <div class="alert alert-danger">해당 댓글을 삭제하실건가요?</div>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="댓글 삭제" class="btn btn-outline-danger">
</form>
{% endblock %}

post/templates/post/comment_list.html
{% for comment in comments %}
    {% include 'post/comment_single.html' %}
{% endfor %}

post/templates/post/comment_single.html
<div class="comment-single" style="margin-bottom: 20px;">
    <div class="img-profile" style="background-image:url({{comment.author.profile.url}})"></div>
    <div style="float:left; height:100%; width:550px; line-height:100%;">
        <div style="display:inline-block; vertical-align:middle; line-height:normal;">
            <p style="padding:10px; border-radius:25px; background-color:rgb(237,237,237); display:inline-block; margin:0">
                <a style="color:rgb(37,71,194); font-weight:bold;" href="#">{{comment.author.last_name}}{{comment.author.first_name}}</a>&emsp;
                <a class="comment-text">{{comment.text}}</a>
            </p>
            <a class="btn-comment-like" href="{% url 'post:comment_like' comment.id %}">&emsp;좋아요 {% if comment.like %}{{comment.like}}개{% endif %}</a>

            {% if user.is_superuser or comment.author == user %}
            <a class="btn-comment-update" href="{% url 'post:comment_update' comment.id %}">&emsp;수정</a>
            <a class="btn-comment-delete" href="{% url 'post:comment_delete' comment.id %}">삭제</a>
            {% endif %}
        </div>
    </div>
    <div style="clear:both;"></div>
</div>

post/templates/post/post_create.html
{% extends 'post-base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div id="post-list">
    <form style="width:800px;" action="" method="post" enctype="multipart/form-data">
        <input type="hidden" name="group_id" value="{{group.id}}">
        {% csrf_token %}
        {{form.media}}
        {{form.as_p}}
        <div style="float:right;">
            <a href="{% url 'post:list' %}?extore={{group.id}}" class="btn btn-outline-primary" style="margin-right:10px;">목록</a>
            <input type="submit" class="btn btn-primary" value="공유하기">
        </div>
    </form>
</div>
{% endblock %}

{% block extra_script %}
{% endblock %}

post/templates/post/post_detail.html
{% extends 'post-base.html' %}

{% block title %}
{% endblock %}

{% block extra_style %}
<style>
.back-to-page {
    width:100px;
    float:right;
    margin-bottom:20px;
}
</style>
{% endblock %}

{% block content %}
<div id="post-list">
    <!--이전 페이지 돌아가기 : onclick="history.go(-1);"-->
    <div>
        <a href="{% url 'post:list' %}?extore={{group.id}}" class="btn btn-primary back-to-page">돌아가기</a>
    </div>
    <div class="card" style="width: 40rem;">
      <div id="profiles">
          <div class="img-profile" style="background-image:url({{object.author.profile.url}})"></div>
          <a class="a-tag name-profile" href="#">{{object.author.last_name}}{{object.author.first_name}}</a>
          <p style="float:right; margin-right:10px; color:rgb(185,185,185);">
              {% load calc %}
              {{object.created|time_since}}
          </p>
      </div>
      <img src="{{object.image.url}}" class="card-img-top">
      <div class="card-body" style="padding:1.25rem 1.25rem 0.5rem 1.25rem;">
         <ul style="list-style-type:none; padding:0">
              <li style="height:30px;margin-bottom:10px;">
                  <a href="{% url 'post:post_like' object.id %}" class="btn-like {% if user in object.like.all %}activate{% endif %}" style="height:30px; margin-right:10px;"></a>
                  <a href="{% url 'post:detail' object.id %}?extore={{group.id}}" class="btn-comment" style="height:30px;"></a>
                  <a href="{% url 'post:post_saved' object.id %}" class="btn-save {% if user in object.saved.all %}activate{% endif %}" style="float:right; height:30px;"></a>
              </li>
              <li class="like-count" style="font-size:15px; font-weight:bold;">
                  좋아요 {{object.like.count}}개
              </li>
              <li class="post-contents" style="margin:10px 0;">
                  <a class="a-tag" href="#"><b>{{object.author.last_name}}{{object.author.first_name}}</b></a>
                  <p class="post-text" style="display:inline-block; margin:0">{{object.text}}</p>
              </li>
              <li>
                  {% load tagging_tags %}
                  {% tags_for_object object as tags %}
                  {% if tags %}
                    {% for tag in tags %}
                        <a class="tags" href="{% url 'post:post_taggedlist' tag.name %}?extore={{group.id}}">#{{tag.name}}</a>
                  {% endfor %}
                  {% endif %}
                  {% if user|author_or_staff:object.author %}
                  <a href="{% url 'post:delete' object.id %}" class="post-delete" style="float:right;">삭제</a>
                  <a href="{% url 'post:update' object.id %}" class="post-update" style="float:right; margin-right:10px;">수정</a>
                  {% endif %}
              </li>
          </ul>
          <div style="height:10px; clear:both;"></div>
      </div>
    </div>
    <div class="card" style="width: 40rem; margin-top:-10px;">
      <div>
          <div class="img-profile" style="background-image:url({{user.profile.url}})"></div>
          <div style="float:right; height:70px; line-height:70px;">
              <div style="display:inline-block; vertical-align:middle; line-height:normal;">
                  <form action="{% url 'post:comment_create' object.id %}" method="post" id="comment_form">
                      {% csrf_token %}
                      <input type="hidden" name="is_ajax" value="">
                      <div class="row" style="width:590px; padding-right:10px;">
                          <div id="comment_write" class="col-8" style="padding:0 0 0 5px;">{{comment_form.text}}</div>
                          <div class="col">
                            <input type="submit" value="댓글 입력" class="btn btn-outline-primary form-control">
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
      <div id="comment_list">
        {% include 'post/comment_list.html' %}
      </div>
    </div>
</div>

{% endblock %}

{% block extra_script %}
<script type="text/javascript">
$(function () {
    $(".post-update").click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        $(".post-update").after("<a href='#' class='post-update-cancel' style='float:right;'>취소</a><a href='#' class='post-update-save' style='float:right; margin-right:10px;'>저장</a>");

        postText = $(this).parent().siblings('.post-contents').children('.post-text');
        input = "<input style='width:540px' class='update-text form-control' value='"+postText.text()+"'>";
        postText.html(input);

        $('.post-update').hide();
        $('.post-delete').hide();

        $('.post-update-cancel').click(function(e){
            e.preventDefault();
            location.reload();
        });
        $('.post-update-save').click(function(e){
            e.preventDefault();
            check = confirm('입력하신 내용으로 수정하시겠습니까?');
            text = $('.update-text').val();
            console.log(text);
            if(check==true){
                $.ajax({
                    url : url,
                    method : 'POST',
                    data : {
                        'csrfmiddlewaretoken' : '{{csrf_token}}',
                        'text' : text,
                    }
                }).done(function(data){
                    if(data.works){
                        alert('게시물이 수정되었습니다.');
                        postText.text(text);
                        $('.post-update-save').hide();
                        $('.post-update-cancel').hide();
                        $('.post-update').show();
                        $('.post-delete').show();
                    } else if(data.noAuthor) {
                        alert('수정 권한이 없습니다.');
                        location.reload();
                    } else {
                        alert('정상 요청이 아닙니다.');
                        location.reload();
                    }
                });
            }
        });
    });


    $(".post-delete").click(function(e){
        e.preventDefault();
        url = $(this).attr('href');
        check = confirm('해당 게시물을 삭제하시겠습니까?');
        $.ajax({
            url : url,
        }).done(function(data){
            if(data.works){
                alert('게시물이 삭제되었습니다.');
                window.location.href = "{% url 'post:list' %}?extore={{group.id}}"
            } else if(data.noAuthor) {
                alert('삭제 권한이 없습니다.');
            } else {
                alert('정상 요청이 아닙니다.');
            }
        });
    });

    $(".btn-like").click(function(e){
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href');
        $.ajax({
            url: url,
            method: "POST",
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'is_ajax': true,
            },
        }).done(function(data){
            if(data.liked){
                selected_object.addClass("activate");
                like_object = selected_object.parents("ul").children(".like-count");
                str_like_content = like_object.html().trim();
                int_like_count = str_like_content.match(/[0-9]/g);
                like_count = parseInt(int_like_count[0]) + 1;
                like_object.html("좋아요 "+like_count+"개")

            }
            else{
                selected_object.removeClass("activate");
                like_object = selected_object.parents("ul").children(".like-count");
                str_like_content = like_object.html().trim();
                int_like_count = str_like_content.match(/[0-9]/g);
                like_count = parseInt(int_like_count[0]) - 1;
                like_object.html("좋아요 "+like_count+"개")
            }
        });
    });

    $(".btn-save").click(function(e){
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href');
        $.ajax({
            url: url,
            method: "POST",
            data: {
                'csrfmiddlewaretoken': '{{csrf_token}}',
                'is_ajax': true,
            },
        }).done(function(data){
        if(data.saved){
            selected_object.addClass("activate");
        }
        else{
            selected_object.removeClass("activate");
        }
        });
    });

    $("#comment_form").submit(function(e){
        e.preventDefault();
        $('input[name="is_ajax"]').val("1");
        url = $(this).attr('action');
        params = $(this).serialize(); // 현재 값들을 하나로 모은다.
        $.ajax({
            url: url,
            method: "POST",
            data: params,
        }).done(function(data){
            location.reload();
        });
    });

    $(".btn-comment-like").click(function(e){
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href')
        console.log(url);
        $.ajax({
            url:url,
            method:"POST",
            data:{
                'csrfmiddlewaretoken':'{{csrf_token}}',
                'is_ajax':true,
            },
        }).done(function(data){
            if(data.works){
                str_comment_like = selected_object.html().trim();
                if(str_comment_like.match(/[0-9]+/g)==null){
                    selected_object.html("&emsp;좋아요 1개")
                }
                else{
                    int_comment_like = str_comment_like.match(/[0-9]+/g);
                    comment_like = parseInt(int_comment_like[0]) + 1;
                    selected_object.html("&emsp;좋아요 "+comment_like+"개")
                }
            }
        });
    });

    $(".btn-comment-delete").click(function(e){
        e.preventDefault();
        var input = confirm('댓글을 삭제하시겠습니까?');
        if (input==true){
            selected_object = $(e.currentTarget);
            url = selected_object.attr('href')+"?is_ajax=1";
            console.log(url);
            $.ajax({
                url: url,

            }).done(function(data){
                if (data.works){
                    selected_object.parents('.comment-single').remove();
                }
            });
        }
    });

    $('.btn-comment-update').click(function(e) {
        e.preventDefault();
        selected_object = $(e.currentTarget);
        url = selected_object.attr('href')+'?is_ajax=1';
        comment = selected_object.siblings('p').children('.comment-text');
        input = "<input type='text' class='update-text' value='"+comment.text()+"'>";
        comment.html(input);
        $('.update-text').keypress(function(e){
            if (e.keyCode==13) {
                text = $(this).val();
                $.ajax({
                    url:url,
                    data:{
                        text:text
                    }
                }).done(function(data) {
                    if(data.works) {
                        comment.text(text);
                    }
                });
            }
        });
    });



});

</script>
{% endblock %}

post/templates/post/tag_list.html
{% extends 'post-base.html' %}

{% block title %}Tag List{% endblock %}

{% block extra_style %}
<style>
    a {
        color: green;
        text-decoration: none;
    }
    a:hover {
        color: yellow;
        text-decoration: none;
    }
</style>
{% endblock %}

{% block content %}

{% load tagging_tags%}

{% tag_cloud_for_model post.Post as post_tags with steps=9 min_count=1 distribution=log %}
    {% for tag in post_tags %}
    <a href="{% url 'post:post_taggedlist' tag.name %}?extore={{group.id}}" style="font-size:{{tag.font_size}}em;">{{tag}}</a>
    {% endfor %}

{% endblock %}