config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.static import serve
from django.urls import re_path
urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('board/', include('board.urls')),
    path('post/', include('post.urls')),
    path('schedule/', include('schedule.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('extore.urls')),
    path('admin/', admin.site.urls),
    # 라이브 상태일 때 S3 연동 없이, serve 뷰 사용하여 media 연결
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('debug/', include(debug_toolbar.urls)),
    ]

# from django.conf.urls.static import static
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('list/', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('detail/<int:post_id>/', post_detail, name='detail'),
    path('update/<int:post_id>/', post_update, name='update'),
    path('delete/<int:post_id>/', post_delete, name='delete'),
    path('tags/<tag>/', PostTaggedObjectList.as_view(), name='post_taggedlist'),
    path('comments/<int:post_id>/', comment_create, name='comment_create'),
    path('like/<int:post_id>/', post_like, name='post_like'),
    path('saved/<int:post_id>/', post_saved, name='post_saved'),
    path('comment/<int:comment_id>/', comment_like, name='comment_like'),
    path('last_memory/', last_memory, name='last_memory'),
    path('comment/update/<int:comment_id>/', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', comment_delete, name='comment_delete'),
]

schedule/urls.py
from django.urls import path
from .views import *

app_name = 'schedule'

urlpatterns = [
    path('', index, name='index'),
    path('create/', schedule_create, name='create'),
    path('list/<int:group_id>/', schedule_list, name='list'),
    path('update/<int:calendarevent_id>/', schedule_update, name='update'),
    path('delete/<int:calendarevent_id>/', schedule_delete, name='delete'),
    path('all_events/<int:group_id>/', all_events, name='all_events'),
]

schedule/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from extore.models import Group

User = get_user_model()

class CalendarEvent(models.Model):
    extore = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='schedules')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="schedules")
    title = models.CharField(_('Title'), max_length=200)
    start = models.DateTimeField(_('Start'))
    end = models.DateTimeField(_('End'))
    all_day = models.BooleanField(_('All day'), default=False)
    # models.DateTimeField(input_formats=["%d %b %Y %H:%M:%S %Z"])
    class Meta:
        verbose_name = _('Event')
        verbose_name_plural = _('Events')

        ordering = ['-start']

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

schedule/forms.py
from django import forms
from .models import *

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = CalendarEvent
        fields = ['title', 'start', 'end']
        widget = {
            'start':forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M']),
            'end':forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M']),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = ''
        self.fields['title'].widget.attrs = {'class':'form-control', 'placeholder':'할 일을 입력하세요.'}
        self.fields['start'].widget.attrs = {'class':'form-control', 'placeholder':'시작일(ex. 2019-06-28 10:00)'}
        self.fields['end'].widget.attrs = {'class':'form-control', 'placeholder':'종료일(ex. 2019-06-28 18:00)'}

schedule/views.py
import math
from urllib.parse import urlparse

from django.db.models import Q
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from .models import CalendarEvent
from extore.models import Group
from .util import events_to_json, calendar_options
from django.contrib import messages
from accounts.models import User
from django.urls import reverse_lazy
from django.template import loader

# This is just an example for this demo. You may get this value
# from a separate file or anywhere you want

OPTIONS = """{  timeFormat: "H:mm",
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay',
                },
                allDaySlot: false,
                firstDay: 0,
                weekMode: 'liquid',
                slotMinutes: 15,
                defaultEventMinutes: 30,
                minTime: 0,
                maxTime: 24,
                editable: false,
                dayClick: function(date, allDay, jsEvent, view) {
                    if (allDay) {       
                        $('#calendar').fullCalendar('gotoDate', date)      
                        $('#calendar').fullCalendar('changeView', 'agendaDay')
                    }
                },
                eventClick: function(event, jsEvent, view) {
                    if (view.name == 'month') {     
                        $('#calendar').fullCalendar('gotoDate', event.start)      
                        $('#calendar').fullCalendar('changeView', 'agendaDay')
                    }
                },
            }"""


def index(request):
    group_id = request.GET.get('extore', None)

    if group_id:
        event_url = f'all_events/{group_id}/'
        group = Group.objects.get(id=group_id)
        group_list = request.user.members_groups.all()
        users = User.objects.all()
        return render(request, 'schedule/index.html', {'calendar_config_options': calendar_options(event_url, OPTIONS), 'group':group, 'group_list':group_list, 'users':users})
    raise Http404



def all_events(request, group_id):
    if group_id:
        events = CalendarEvent.objects.filter(extore_id=group_id)
        return HttpResponse(events_to_json(events), content_type='application/json')
    raise Http404


from .forms import ScheduleForm
from django.urls import reverse
from django.shortcuts import redirect


def schedule_create(request):
    if request.method == "POST":
        form = ScheduleForm(request.POST, request.FILES)

        form.instance.author_id = request.user.id
        form.instance.extore_id = request.POST.get('group_id', None)

        if request.POST.get('start') >= request.POST.get('end'):
            return JsonResponse({'wrongDateTime':True})

        if len(request.POST.get('title')) > 60:
            return JsonResponse({'tooLongTitle':True})

        if form.is_valid():
            # schedule = form.save()
            # group_id = schedule.extore_id
            # return redirect(reverse('schedule:list', args=[group_id]))
            form.save()
            return JsonResponse({'works': True})

        else:
            return JsonResponse({'notValid':True})
            # group_id = form.instance.extore_id
            # group = Group.objects.get(id=group_id)
            # group_list = request.user.members_groups.all()
            # users = User.objects.all()
            #
            # messages.warning(request, '입력이 올바르지 않습니다.')
            # return render(request, 'schedule/schedule_create.html', {'form':form, 'group':group, 'group_list':group_list, 'users':users})

    else:
        group_id = request.GET.get('extore', None)
        if group_id:
            form = ScheduleForm()
            group = Group.objects.get(id=group_id)
            group_list = request.user.members_groups.all()
            users = User.objects.all()

            return render(request, 'schedule/schedule_create.html', {'form':form, 'group':group, 'group_list':group_list, 'users':users})

        raise Http404


def schedule_list(request, group_id):
    if group_id:
        schedules = CalendarEvent.objects.filter(extore_id=group_id)
        group = Group.objects.get(id=group_id)
        group_list = request.user.members_groups.all()
        users = User.objects.all()

        page = int(request.GET.get('page', 1))
        paginated_by = 6

        search_type = request.POST.getlist('search_type', None) if request.method == "POST" else request.GET.get(
            'searchType', None)

        search_q = None
        search_key = request.POST.get('search_key', None) if request.method == "POST" else request.GET.get('searchKey',
                                                                                                           None)

        # 검색어 입력한 경우
        if search_key:
            if 'title' in search_type:
                temp_q = Q(title__icontains=search_key)
                search_q = search_q | temp_q if search_q else temp_q
            if 'realName' in search_type:
                last_name = search_key[0]
                first_name = search_key[1:]
                temp_q = Q(author__last_name=last_name) & Q(author__first_name=first_name)
                search_q = search_q | temp_q if search_q else temp_q
            if len(search_type) == 0:
                total_count = len(schedules)
                total_page = math.ceil(total_count / paginated_by)
                page_range = range(1, total_page + 1)
                start_index = paginated_by * (page - 1)
                end_index = paginated_by * page
                schedules = schedules[start_index:end_index]
                return render(request, 'schedule/schedule_list.html', {'object_list': schedules, 'group': group, \
                                                                       'group_list': group_list, 'users': users,
                                                                       'total_page': total_page,
                                                                       'page_range': page_range})


            schedules = schedules.filter(search_q)
            total_count = len(schedules)
            total_page = math.ceil(total_count / paginated_by)
            page_range = range(1, total_page + 1)
            start_index = paginated_by * (page - 1)
            end_index = paginated_by * page
            schedules = schedules[start_index:end_index]
            return render(request, 'schedule/schedule_list.html', \
                          {'object_list': schedules, 'group': group, 'group_list': group_list, \
                           'users': users, 'total_page': total_page, 'page_range': page_range, 'searchKey': search_key,
                           'searchType': search_type})

        # 검색어 입력하지 않고 목록 조회하는 경우
        total_count = len(schedules)
        total_page = math.ceil(total_count / paginated_by)
        page_range = range(1, total_page + 1)
        start_index = paginated_by * (page - 1)
        end_index = paginated_by * page
        schedules = schedules[start_index:end_index]
        return render(request, 'schedule/schedule_list.html', {'object_list': schedules, 'group':group, \
                                                       'group_list':group_list, 'users':users, 'total_page':total_page, 'page_range':page_range})
    raise Http404


def schedule_update(request, calendarevent_id):
    schedule = CalendarEvent.objects.get(pk=calendarevent_id)
    if request.method == "POST":
        form = ScheduleForm(request.POST, instance=schedule)
        if form.is_valid():
            form.save()
            group_id = request.POST.get('group_id', None)

            return redirect(reverse('schedule:list', args=[group_id]))
        else:
            messages.warning(request, '입력이 올바르지 않습니다.')
            group_id = request.POST.get('group_id', None)

            return redirect(reverse('schedule:list', args=[group_id]))
    else:
        group_id = request.GET.get('extore', None)
        group = Group.objects.get(id=group_id)
        group_list = request.user.members_groups.all()
        form = ScheduleForm(instance=schedule)
        users = User.objects.all()
    return render(request, 'schedule/schedule_update.html', {'form':form, 'group':group, 'group_list':group_list, 'users':users})


def schedule_delete(request, calendarevent_id):
    schedule = CalendarEvent.objects.get(pk=calendarevent_id)
    if request.method == "POST":
        print(schedule.author.username, request.user)
        if schedule.author != request.user and not request.user.is_staff:
            messages.warning(request, '삭제할 권한이 없습니다.')

            group_id = request.POST.get('group_id', None)
            # schedules = CalendarEvent.objects.filter(extore_id=group_id)
            # group = Group.objects.get(id=group_id)
            # group_list = request.user.members_groups.all()

            return redirect(reverse('schedule:list', args=[group_id]))

        else:
            schedule.delete()
            group_id = request.POST.get('group_id', None)
            # schedules = CalendarEvent.objects.filter(extore_id=group_id)
            # group = Group.objects.get(id=group_id)
            # group_list = request.user.members_groups.all()
            # return render(request, 'schedule/schedule_list.html', {'object_list':schedules, 'group':group, 'group_list':group_list})
            return redirect(reverse('schedule:list', args=[group_id]))

    else:
        if request.is_ajax():
            schedule = CalendarEvent.objects.get(pk=calendarevent_id)
            if request.user != schedule.author and not request.user.is_staff:
                return JsonResponse({'notAuthor':True})
            schedule.delete()
            return JsonResponse({'works': True})

        else:
            group_id = request.GET.get('extore', None)
            group = Group.objects.get(id=group_id)

schedule/templates/schedule/calandar.html
<div id="calendar"></div>

schedule/templates/schedule/calendar_init.html
<script type="text/javascript">
    $(document).ready(function() {
        // page is now ready, initialize the calendar...
        $('#calendar').fullCalendar({{ calendar_config_options }});
    });
</script>

schedule/templates/schedule/index.html
{% extends "schedule-base.html" %}

{% load fullcalendar_tags %}

{% block content %}
<div id="schedule-index">
	<div style="width:800px; margin:0 auto; text-align:right;">
		<a href="{% url 'schedule:list' group.id %}" class="btn btn-outline-primary" style="margin-right:10px;">일정 관리</a>
		<a href="{% url 'schedule:create' %}?extore={{group.id}}" class="btn btn-primary">할일 작성</a>
	</div>
	<div style="height:800px; line-height:800px; width:800px; margin:0 auto;">
		<div style="width:800px; display:inline-block; vertical-align:middle; line-height:normal;">
			{% calendar %}
		</div>
	</div>
</div>
{% endblock %}

schedule/templates/schedule/schedule_create.html
{% extends 'schedule-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="'col-sm-8 col-md-8 col-lg-8">
            <div class="form-group">
                <form action="" method="post" id="schedule-create">
                    <input type="hidden" name="group_id" value="{{group.id}}">
                    {% csrf_token %}
                    <ul style="list-style:none;">
                        <li style="margin:20px;">{{form.title}}</li>
                        <li style="margin:20px;">{{form.start}}</li>
                        <li style="margin:20px;">{{form.end}}</li>
                    </ul>
                    <div style="float:right;">
                        <a href="{% url 'schedule:index' %}?extore={{group.id}}" class="btn btn-outline-primary" style="margin-right:10px;">목록</a>
                        <input type="submit" class="btn-push btn btn-primary" value="입력하기">
                    </div>
                </form>
            </div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block extra_script %}
<script>
$(function () {
    $('#schedule-create').submit(function(e){
        e.preventDefault();
        var url = "{% url 'schedule:create' %}"
        var form = $(this)[0]
        var formData = new FormData(form)
        $.ajax({
            url : url,
            processData: false,
            contentType: false,
            cache: false,
            type: "POST",
            data: formData,
        }).done(function(data){
            if(data.works){
                alert('일정을 생성하였습니다.');
                window.location.href = "{% url 'schedule:list' group.id %}"
            } else if(data.tooLongTitle){
                alert('내용은 60자를 초과할 수 없습니다.');
            } else if(data.notValie){
                alert('입력 내용이 올바르지 않습니다.');
            } else if(data.wrongDateTime){
                alert('종료일은 시작일보다 나중이어야 합니다.');
            } else {
                alert('정상 요청이 아닙니다.');
            }
        }).fail(function(xhr, textStatus, errorThrown){
            alert(xhr.responseText);
        });
    });
});
</script>
{% endblock %}

schedule/templates/schedule/schedule_delete.html
{% extends 'schedule-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}

{% endblock %}

{% block content %}
    <form action="" method="post">
        <input type="hidden" name="group_id" value="{{group.id}}">
        {% csrf_token %}
        <a href="{% url 'schedule:list' group.id %}" class="btn btn-outline-primary" style="margin-right:10px;">목록</a>
        <input type="submit" class="btn btn-primary" value="Delete">
    </form>

{% endblock %}

schedule/templates/schedule/schedule_list.html
{% extends 'schedule-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}
<style>
    .screen {
        text-align: center;
    }
    .profiles {
        height: 68px;
        line-height: 68px;
        list-style-type: none;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
{% load calc %}
<div style="width:880px; display:inline-block; text-align:right;">
    <a href="{% url 'schedule:index' %}?extore={{group.id}}" class="btn btn-primary">캘린더 보기</a>
</div>
<div style="width:1000px; margin:0 auto; text-align:center;">
    <div style="display: inline-block;">
        {% if object_list %}
        {% for object in object_list %}
        <div class="card schedule-div" style="margin: 15px; width:18rem; float:left;">
            <ul class="list-group list-group-flush">
                <li class="profiles">
                    <div class="img-profile" style="background-image:url({{object.author.profile.url}})"></div>
                    <a class="a-tag name-profile" >{{object.author.last_name}}{{object.author.first_name}}</a>
                </li>
                <li class="list-group-item" style="height:150px;">
                    <div style="height:120px;line-height:120px;display:block;">
                        <div style="line-height:normal;vertical-align:middle;display:inline-block;">
                            {{object.title}}
                        </div>
                    </div>
                </li>
                <li class="list-group-item">{{object.start}}</li>
                <li class="list-group-item">{{object.end}}</li>
            </ul>
            {% if user|author_or_staff:object.author %}
            <div class="card-body" style="text-align:center;">
                <a href="{% url 'schedule:update' object.id %}?extore={{group.id}}" style="margin:0 35px;" class="card-link">Update</a>
                <a href="{% url 'schedule:delete' object.id %}?extore={{group.id}}" style="margin:0 35px;" class="card-link schedule-delete">Delete</a>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        {% else %}
        <div style="height:558px; line-height:558px; text-align:center;">
            <div style="display:inline-block; line-height:558px; vertical-align:middle;"> 게시물이 없습니다.</div>
        </div>
        {% endif %}
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for page in page_range %}
                {% if searchKey %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'schedule:list' group.id %}?searchKey={{searchKey}}&searchType={{searchType}}&page={{page}}">{{page}}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'schedule:list' group.id %}?page={{page}}">{{page}}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

    <form action="{% url 'schedule:list' group.id %}" method="post" id="search_form">
        {% csrf_token %}
        <div class="form-row align-items-center justify-content-center">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="realName" name="search_type" checked>
                <label class="form-check-label" for="inlineCheckbox1">작성자</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="title" name="search_type">
                <label class="form-check-label" for="inlineCheckbox3">내용</label>
            </div>
        </div>
        <div class="form-row align-items-center justify-content-center">
            <div class="col-sm-3 my-1">
                <input type="text" class="form-control" placeholder="검색어" name="search_key">
            </div>

            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">검색하기</button>
            </div>
        </div>
    </form>


</div>
{% endblock %}

{% block extra_script %}
<script>
$(function(){
    $('.schedule-delete').click(function(e){
        e.preventDefault();
        var url = $(this).attr('href');
        var check = confirm('해당 일정을 삭제하시겠습니까?');
        var selected = $(this);
        if(check == true){
            $.ajax({
                url : url,
            }).done(function(data){
                if(data.works){
                    alert('일정이 삭제되었습니다.');
                    selected.parents('.schedule-div').remove();
                } else if(data.notAuthor) {
                    alert('삭제할 권한이 없습니다.');
                } else {
                    alert('정상 요청이 아닙니다.');
                }
            });
        }
    });
});

</script>
{% endblock %}

schedule/templates/schedule/schedule_update.html
{% extends 'schedule-base.html' %}
{% block title %}
{% endblock %}

{% block extra_style %}

{% endblock %}

{% block content %}
<div id="post-list">
    <form action="" method="post">
        <input type="hidden" name="group_id" value="{{group.id}}">
        {% csrf_token %}
        <ul style="list-style:none; margin:0; padding:0;">
            <li style="margin-bottom:20px;">{{form.title}}</li>
            <li style="margin-bottom:20px;">{{form.start}}</li>
            <li style="margin-bottom:20px;">{{form.end}}</li>
        </ul>
        <div style="float:right;">
            <a href="{% url 'schedule:list' group.id %}" class="btn btn-outline-primary" style="margin-right:10px;">목록</a>
            <input type="submit" class="btn-push btn btn-primary" value="수정하기">
        </div>
    </form>
</div>
{% endblock %}